# Generated by Django 4.2.6 on 2023-10-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0002_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timing',
            field=models.DateField(null=True),
        ),
    ]
