# Generated by Django 4.2.6 on 2023-10-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0004_alter_post_timing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timing',
            new_name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
