# Generated by Django 4.2.6 on 2023-10-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0005_rename_timing_post_date_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
